/*
 * mod-profession-loot-party
 *
 * AzerothCore WotLK 3.3.5a
 *
 * Gives eligible group/raid members independent profession-loot
 * rolls when another member successfully gathers a resource.
 *
 * Supported professions:
 *
 *   - Mining
 *   - Herbalism
 *   - Skinning
 *
 * Supported gathering implementations:
 *
 *   - Normal AzerothCore gathering
 *   - mod-auto-gather Mining/Herbalism
 *   - mod-auto-gather Skinning
 *
 * The original gatherer/skinner keeps their normal loot.
 *
 * Profession multipliers:
 *
 *   Multiplier = 1:
 *       Gatherer    -> normal AzerothCore/AutoGather loot
 *       Other       -> 1 independent roll
 *
 *   Multiplier = 3:
 *       Gatherer    -> normal loot + 2 independent rolls
 *       Other       -> 3 independent rolls
 *
 * The multiplier therefore represents the TOTAL number of loot
 * rolls each eligible profession user receives for the gathering
 * operation.
 */

#ifndef PROFESSION_LOOT_PARTY_H
#define PROFESSION_LOOT_PARTY_H

#include "AllGameObjectScript.h"
#include "Define.h"
#include "ObjectGuid.h"
#include "PlayerScript.h"
#include "WorldScript.h"

class Creature;
class GameObject;
class Player;
class Unit;

namespace ProfessionLootParty
{
    struct PendingGather
    {
        ObjectGuid gatherer;
        ObjectGuid gameObject;
        uint32 createdAt = 0;
    };

    /*
     * Used to prevent the same skinned corpse from being processed
     * more than once.
     *
     * Skinning has no GameObject loot-state callback equivalent
     * to normal Mining/Herbalism gathering.
     */
    struct RecentSkinning
    {
        ObjectGuid gatherer;
        ObjectGuid creature;
        uint32 createdAt = 0;
    };

    bool IsEnabled();

    bool IsProfessionEnabled(uint32 skillId);

    /*
     * Returns the configured TOTAL number of rolls for a profession.
     *
     * 0 = no module-generated rolls
     * 1 = one total roll
     * 3 = three total rolls
     * etc.
     */
    uint32 GetProfessionMultiplier(uint32 skillId);

    /*
     * Normal AzerothCore Mining/Herbalism gathering.
     */
    void AddPendingGather(
        Player* gatherer,
        GameObject* gameObject);

    void RemovePendingGather(
        ObjectGuid playerGuid);

    bool ProcessPendingGather(
        Player* gatherer,
        uint32 skillId);

    /*
     * mod-auto-gather Mining/Herbalism compatibility.
     */
    void ProcessAutoGather(
        Player* gatherer,
        uint32 skillId);

    /*
     * Skinning.
     *
     * Handles both:
     *
     *   - normal AzerothCore Skinning
     *   - mod-auto-gather AutoSkinCreature()
     */
    bool ProcessSkinning(
        Player* skinner);

    void RemoveRecentSkinning(
        ObjectGuid playerGuid);

    class PlayerScript final : public ::PlayerScript
    {
    public:
        PlayerScript();

        void OnPlayerUpdateGatheringSkill(
            Player* player,
            uint32 skillId,
            uint32 currentLevel,
            uint32 gray,
            uint32 green,
            uint32 yellow,
            uint32& gain) override;

        void OnPlayerLogout(
            Player* player) override;
    };

    class GameObjectScript final : public ::AllGameObjectScript
    {
    public:
        GameObjectScript();

        void OnGameObjectLootStateChanged(
            GameObject* gameObject,
            uint32 state,
            Unit* unit) override;
    };

    class ConfigScript final : public ::WorldScript
    {
    public:
        ConfigScript();

        void OnBeforeConfigLoad(
            bool reload) override;
    };
}

/*
 * AzerothCore module loader.
 *
 * Keep this exact spelling/capitalization consistent with the
 * module loader generated by AzerothCore.
 */
void Addmod_profession_loot_partyScripts();

#endif